/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 cube.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cube.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Image ONE']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Image TWO']} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Image THREE']} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials['Image FOUR']} />
      <mesh geometry={nodes.Cube_5.geometry} material={materials['Image FIVE']} />
      <mesh geometry={nodes.Cube_6.geometry} material={materials['Image SIX']} />
    </group>
  )
}

useGLTF.preload('/cube.glb')
